- hosts: control
  tasks:
    - name: Initialize the cluster
      shell: |
        if [[ -f init.txt ]]
        then
          echo "init.txt cluster file already exist"
        else
          kubeadm init --pod-network-cidr=10.11.0.0/16 > init.txt
        fi
    - name: Copy admin.conf to user's kube config
      shell: |
        mkdir -p $HOME/.kube
        /usr/bin/cp  /etc/kubernetes/admin.conf $HOME/.kube/config
        chown $(id -u):$(id -g) $HOME/.kube/config

    - name: Install calico Pod network
      shell: |
        curl https://raw.githubusercontent.com/projectcalico/calico/v3.30.2/manifests/calico.yaml -O
        kubectl apply -f calico.yaml